### ISSUE TITLE
Fortify::authenticateUsing called twice

### ISSUE THREAD

**Issue by oulfr** [laravel/fortify#339] opened 2022-01-08 16:34 UTC
- Fortify Version: 1.8
- Laravel Version: 8.65
- PHP Version: 8.0
- Database Driver & Version:

### Description:
The **Fortify::authenticateUsing** method is triggered twice for each request.

### Steps To Reproduce:
In FortifyServiceProvider create an index:
     `protected  $i=1;`

In boot method add tis function:

        Fortify::authenticateUsing(function (Request $request) {
            $this->i++;

            if( $this->i > 2){
                dd('hmm', $this->i);
            }
            $user = User::where('email', $request->email)->first();
            if ($user && Hash::check($request->password, $user->password)) {
                return $user;
            }
        });

        Fortify::loginView(function () {
            return view('user::auth.login');
        });

You will get: 
            "hmm"
            3

**Comment by driesvints** [comment] 2022-01-08 16:40
I'm not really sure what the issue is. If you can post much more clear description what is amis and how it blocks you with clear steps to reproduce then we can have another look. Thanks

**Comment by oulfr** [comment] 2022-01-08 16:51
The issue is the **Fortify::authenticateUsing** method is triggered twice.
It should be called one time for each request

**Comment by driesvints** [comment] 2022-01-08 17:02
I'll try it on Monday

**Comment by driesvints** [comment] 2022-01-10 15:11
Bit swamped with Laravel 9 stuff right now so I'm delaying this until I find some time.

**Comment by driesvints** [comment] 2022-01-17 10:59
I indeed get the same thing but since there's no actual bug and nothing's broken I'm going to close this. If you can help us optimize this we'd appreciate a PR. Thanks

**Closed by driesvints** 2022-01-17 10:59 UTC
Labels: needs more info

**Comment by ricardogobbosouza** [comment] 2022-01-17 13:47
Hi @oulfr 
It actually happens...see https://github.com/laravel/fortify/pull/304

**Comment by driesvints** [comment] 2022-01-17 13:50
@ricardogobbosouza I didn't know about that PR anymore. Looks like this is a wont fix, sorry.

**Comment by ricardogobbosouza** [comment] 2022-01-17 13:51
The authentication method is called twice when the `twoFactorAuthentication` feature is enabled

https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/AuthenticatedSessionController.php#L86-L87

**Comment by oulfr** [comment] 2022-01-19 09:47
this bug is blocked if we want to add google recaptcha validation to the authentication form, because the google recaptcha api only authorizes the first request and it considers the second call as a bot and never the validation will pass.
to resolve the issue we have implemented something like this:

              class FortifyServiceProvider extends ServiceProvider
              {
                  protected $isFirstCall = false;
	              
	              public function boot()
                  {
                      
                      Fortify::authenticateUsing(function ($request) {
                          if (!$this->isFirstCall) {
                              $this->isFirstCall = true;
                              $request->validate([
                                  'g-recaptcha-response' => ['required', new CaptchaRule],
                              ]);
                          }
                          $validated = Auth::validate($credentials = [
                              'email' => $request->email,
                              'password' => $request->password
                          ]);
                          $user = Auth::getProvider()->retrieveByCredentials($credentials);
                          return $validated && $user->isActive() ? $user : null;
                      });
		              
	              }
	              
              }

**Comment by dirkam** [comment] 2023-02-03 11:11
This is also (or might be) a problem, if you try to authenticate the user from a remote data source. For instance, in the case of LDAP login or similar remote repository, multiple calls are made. Since these require network connections, it can cause issues. And, as @oulfr mentioned, some third-parties might consider this as a bot activity and block the request.

Would it be possible to reopen this issue and fix this behavior?

**Comment by driesvints** [comment] 2023-02-03 12:04
Right now we're not actively looking to fix this sorry. But you can always try another PR to change Taylor's mind.

**Comment by oulfr** [comment] 2023-02-03 12:23
@driesvints :yes I know this is a bug, and I stopped to participate to this project because each time I open an issue the laravel teams close it automatically, and I never see this behavior in other open source project

**Comment by driesvints** [comment] 2023-02-03 12:27
I'm sorry you feel this way @oulfr. In general issues we don't want to tackle ourselves or not actually consider an issue, like this one, will be closed to keep our issue queue clear.

**Comment by kingroho** [comment] 2023-08-31 01:19
Wow, I've been dealing with this problem for hours now. Turns out, this function is indeed running twice. That's why Cloudflare's Turnstile is not working for me. Anyway, glad I'm not alone. WIll try to disable 2FA see if that solves the issue.

**Comment by gtim04** [comment] 2024-01-29 16:08
> this bug is blocked if we want to add google recaptcha validation to the authentication form, because the google recaptcha api only authorizes the first request and it considers the second call as a bot and never the validation will pass. to resolve the issue we have implemented something like this:
> 
> ```
>           class FortifyServiceProvider extends ServiceProvider
>           {
>               protected $isFirstCall = false;
>               
>               public function boot()
>               {
>                   
>                   Fortify::authenticateUsing(function ($request) {
>                       if (!$this->isFirstCall) {
>                           $this->isFirstCall = true;
>                           $request->validate([
>                               'g-recaptcha-response' => ['required', new CaptchaRule],
>                           ]);
>                       }
>                       $validated = Auth::validate($credentials = [
>                           'email' => $request->email,
>                           'password' => $request->password
>                       ]);
>                       $user = Auth::getProvider()->retrieveByCredentials($credentials);
>                       return $validated && $user->isActive() ? $user : null;
>                   });
> 	              
>               }
>               
>           }
> ```

this helped me so much. thank you

**Comment by driesvints** [comment] 2024-04-26 07:20
I'm very sorry everyone but looks like this is an absolute no-fix for us. We just don't want to risk breaking something for people.

What you could always do is extend and bind the `AttemptToAuthenticate` action in a service provider to the container and then overwrite the `handleUsingCustomCallback` like in PR https://github.com/laravel/fortify/pull/532. Likewise for `RedirectIfTwoFactorAuthenticatable`.

**Comment by tobz-nz** [comment] 2024-12-18 23:34
Just to jump on this bandwagon even though its old - as I'm getting this issue too, and I'm not even using 2FA.
It seems that the `SendEmailVerificationNotification` listener is getting registered twice:

I've not verified but my hunch is once by the framework itself and again by fortify?

```
// dd(app('events));

Illuminate\Events\Dispatcher {#42 ▼
  #container: Illuminate\Foundation\Application {[#7](https://alttune.ai.localhost/register#sf-dump-1378978117-ref27) …44}
  #listeners: array:38 [▼
    "Illuminate\Console\Events\CommandFinished" => array:1 [▶]
    "Illuminate\Queue\Events\JobAttempted" => array:1 [▶]
    "Illuminate\Queue\Events\JobProcessing" => array:6 [▶]
    "Illuminate\Database\Events\QueryExecuted" => array:3 [▶]
    "Illuminate\Queue\Events\JobProcessed" => array:5 [▶]
    "Illuminate\Auth\Events\Login" => array:1 [▶]
    "Illuminate\Auth\Events\Logout" => array:2 [▶]
    "Laravel\Horizon\Events\JobPushed" => array:2 [▶]
    "Laravel\Horizon\Events\JobReserved" => array:2 [▶]
    "Laravel\Horizon\Events\JobReleased" => array:1 [▶]
    "Laravel\Horizon\Events\JobDeleted" => array:2 [▶]
    "Laravel\Horizon\Events\JobsMigrated" => array:1 [▶]
    "Illuminate\Queue\Events\JobExceptionOccurred" => array:3 [▶]
    "Illuminate\Queue\Events\JobFailed" => array:4 [▶]
    "Laravel\Horizon\Events\JobFailed" => array:2 [▶]
    "Laravel\Horizon\Events\MasterSupervisorLooped" => array:5 [▶]
    "Laravel\Horizon\Events\SupervisorLooped" => array:3 [▶]
    "Laravel\Horizon\Events\LongWaitDetected" => array:1 [▶]
    "Illuminate\Log\Events\MessageLogged" => array:2 [▶]
    "Illuminate\Console\Events\CommandStarting" => array:1 [▶]
    "Illuminate\Cache\Events\CacheHit" => array:1 [▶]
    "Illuminate\Cache\Events\CacheMissed" => array:1 [▶]
    "Illuminate\Queue\Events\JobReleasedAfterException" => array:2 [▶]
    "Illuminate\Queue\Events\JobQueued" => array:2 [▶]
    "Laravel\Pulse\Events\SharedBeat" => array:1 [▶]
    "Laravel\Pulse\Events\IsolatedBeat" => array:1 [▶]
    "Laravel\Reverb\Events\MessageSent" => array:1 [▶]
    "Laravel\Reverb\Events\MessageReceived" => array:1 [▶]
    "Laravel\Pulse\Events\ExceptionReported" => array:1 [▶]
    "Laravel\Octane\Events\RequestReceived" => array:1 [▶]
    "Laravel\Octane\Events\TaskReceived" => array:1 [▶]
    "Laravel\Octane\Events\TickReceived" => array:1 [▶]
    "Illuminate\Foundation\Http\Events\RequestHandled" => array:1 [▶]
    "Illuminate\Foundation\Events\LocaleUpdated" => array:1 [▶]
    "SocialiteProviders\Manager\SocialiteWasCalled" => array:1 [▶]
    "Illuminate\Auth\Events\Registered" => array:2 [▼
      0 => "Illuminate\Auth\Listeners\SendEmailVerificationNotification"
      1 => "Illuminate\Auth\Listeners\SendEmailVerificationNotification"
    ]
    "Illuminate\Queue\Events\Looping" => array:1 [▶]
    "Illuminate\Queue\Events\WorkerStopping" => array:1 [▶]
  ]
  #wildcards: []
  #wildcardsCache: array:17 [▶]
  #queueResolver: Closure() {#41 ▶}
  #transactionManagerResolver: Closure() {#43 ▶}
```

**Comment by tobz-nz** [comment] 2024-12-18 23:48
MIght have found the issue: my `App\Providers\EventServiceProvider` is extending `Illuminate\Foundation\Support\Providers\EventServiceProvider` which registers some stuff twice.

.. Is this extends normal? doesn't seem like something I'd do myself. I checked some other projects and they do it as well.
Is it a change from L10 -> 11 that has not been caught? yes I think so as the `EventServiceProvider` was removed and its handled differently in `bootstrap/app.php` now.

```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;

class EventServiceProvider extends ServiceProvider
```

Right, had to talk that all through, good chat 😁  - leaving this here for others.

**Comment by oulfr** [comment] 2024-12-19 08:46
I reported this issue two years ago, but the way it was managed doesn't seem to address the problem. It feels like they didn’t try to understand the issue and just closed it directly. :)

**Comment by nipunTharuksha** [comment] 2025-06-27 19:05
We also had this issue last year. what we did was altering [authentication pipeline](https://laravel.com/docs/8.x/fortify#customizing-the-authentication-pipeline) to include recaptcha token validation as a middleware like below

```
Fortify::authenticateThrough(function (Request $request) {
            return [
                VerifyTurnstileToken::class,
                AttemptToAuthenticate::class,
                PrepareAuthenticatedSession::class,
            ];
        });
```
