### ISSUE TITLE
[Feature Request] Add WebAuthn

### ISSUE THREAD

**Issue by GunniBusch** [laravel/fortify#541] opened 2024-06-05 13:30 UTC
Hi,
would it be possible to add WebAuthn? 
This would allow for an even better login experience.

**Comment by crynobone** [comment] 2024-06-05 13:45
Duplicate of #22

**Closed by crynobone** 2024-06-05 13:45 UTC

**Comment by GunniBusch** [comment] 2024-06-05 14:12
> Duplicate of #22

Yeah, but that was 4 years ago. Now Webauthn is becoming more common. And this would be a nice feature, since more and more people are using this.

**Comment by jhdxr** [comment] 2025-10-02 03:24
Agreed. Now it's almost the end of 2025, and the nature of Webauthn is very different from 2020. Windows/iOS/android has built-in support for it for years, and all the popular websites are using passkeys to replace 2FA or even the whole login (username+password).
